imTemplate
        coordinates
        DFF 
        npBWout 
        rawFluo 
        roiBW2
        xcRaw 
        ycRaw 
        norm_meanIMG
        symmFLAG
        smoothwin
        r
        dffwindow
        percent
        last_init_frame
        displayWin
        batch_size 
        rank1
        rank2
        rank3
        select1
        select2
        select3
        selectedCellList
        selectedCellsAll
        selectedCellFrameID
        selectQueue
        hidden
        gap
        exptId
        exptVars
        filled
        minNpSubFluo
        maxAdjF
        numInitFrames
        mst
        mstWin
        numAvailFrames
        imagingFreq
        currentFr
        thorSyncFile
        psignalFile
        rawFileHandle
        greenChannel
        numChannels
        scope
        imgType
        ImageFile
        JiSignalInfo
        norm_meanRedIMG
        redChanDisplayed
        meanIMGhandle
        tstack
        xx
        yy
        selectedID
        loadCorrelated
        loadSelected
        groupId
        dll_name
        board_number
        SLM_ON
        SLM;
        stimShutter
        topRankedCellIDs
        target_cellIDs
        debugMode
        debugIndex
        stimulationParams