function centroids = locateCentroids(complexDynamicsPath, env)
    % Locates centroids from image.
    [status, cmdout] = system("" + ...
        "source ~/.bashrc;" + ...
        "source ~/.bash_profile;" + ...
        "which python;" + ...
        "conda activate " + env + ";" + ...
        "python tools/python/locateCentroids.py " + complexDynamicsPath + ";"...
        ...
        );
    disp(cmdout);
    disp(complexDynamicsPath);
end