function neuroArtConfigInit(filename)
    % Write config file for neuroART.
    s = struct( ...
            'R', 5,...
            'DISPLAY', 200,...
            'EXID', 'RT_test1', ...
            'IMGFOLDER', pwd,...
            'IMG', 'Image_0001_0001', ...
            'RF', 2, ...
            'CFIND', 3, ...
            'SLM', 1, ...
            'CWINF', 5 ...
        );
    fid = fopen(filename, 'w');
    fprintf(fid, '%s', jsonencode(s, PrettyPrint=true));
end